env:
  global:
    - secure: "ONLQb/MA9TxN8+xSadAKVAAvoeSqkX5U4RTan85IU4cGxu20o0PRzhfOrB8IPAqjmJ3Hzt95LQWH07otTuINMTSTO8EuPR0++yS9VAjexH2vy3Qxo4orUqBmlztzvBb+iTxxyei3Qw6Ncy4TVpdUOazL2lg3U4nHjW6O/CpXE18FcFBTc1EQEty+/rKcTMi1/RSkSnczg5VBZCPC6KS5z5xWrP/wJ0zqEjqUTJw/E55hJgtkMk2xiXu/nZl3DuUwbN5zJCgYp/iY3Bzc/zp0u5qzlKWZVXNVVLJIVgqX4ge3bK4KtK2E7BhDkP44ss/5SVFXc+yeFjr6xhE/VaXeYigSk6ShZGpbmJKNdpswJ4MS0RkMk24vlNp3qwF7Kzy18pJi3snt1ZP/sw9v1QMpEZ9HyIw/1xoOBwLXGOWRpqNfiT89eW05HFw2Fja9ZgTs0lXuFbmKJ8cXjJtUqT2YO9GOXhNydklbuw1ycBcCL9omrLQz7uPEyiPAMMwWMDOHYgW8aAeTYehwzRg1d2C0IoiDJ5z2714OdSyxAHNV9N+Jd/+70YRXYiOuW3FaKEixCTPWyU1zS0GYWclbbecTdEMmbn+oItHHQ3ZRzo8lSn0+7Rq5Jr6YUF4zmwxVMRKRoQuzP3xfuhbF5bL0VL1wyEYBvqRvifdCpKXTG/93mTI="
    - secure: "lj2EOeytzkA1GhV153EWuVVcAqSqynT/fKL5qz3Nj1DdJZQf0rVNwLlEz59fPq6eSg/8K3XnrcfyVdzbzR5zoN9Wv2c78cWiIfRGJ6tJ3HZSVaR6Qi1DSTFPBCZ3TsYvvxMS7mzZ3sGWW/nPnqw8aPDcF7HQ/p76NW+jEyYT8fO1XLK885WeC9IRed4AGHlW+58FrXqMn3PQ/39YKvQcq4DDQ0DRQKa6hjZ6h56UGeyyjIvBnTIJeWt0xEOUDUKOW/Rq39mltSMRm0KDfOFOq3qkvpPFwPuWDvopTEY7HRtMOR+0bCy1qnpKJ3cfdoBlfxMBTDb5sQ+Mgy6ZCzuWlKUMn6nrsE1BU6sS/kOPmtfg1aq2FHKvcH6x36Ehzum7MODR2gFsCsrU5Cgae2hSoY0ts2FMu/94w8szIJ91oxtpIOghrtXa9oSW7m0wqFzOmAJnksW8qru23DIJI6eLf+rB+uE4fuxN6o9w7oBa+/r2ZBq1bwxdQqPiyLM+syVWrjyfFPc9kK/p9GXpGfDyP91c3h2SNHhZqcGtwd2s6VEpB9mx3EFAtXtGteHjx6S19eKC2ww2JgFFOppQE05fXKUvqfkr3GzzCMrfCxsGbGy9G9di7Dk2yFZph9AZIko93Wt6dFxEyi5roHoa6OqOavU1iuah9ih51NsC9I4yWp0="

sudo: required

cache:
  directories:
    - bundle

services:
  - docker

before_install:
  - npm install vnu-jar
  - sudo mkdir -m 777 build
  - [ -d bundle ] || sudo mkdir -m 777 bundle

script:
  - docker-compose run jekyll jekyll build
  - java -jar node_modules/vnu-jar/build/dist/vnu.jar --skip-non-html --errors-only --filterfile tests/config/vnufilter.txt build/

after_success:
  - >
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ] ;
    then
    export DEPLOY_CONTENT='{"TRAVIS_BUILD_NUMBER":"'$TRAVIS_BUILD_NUMBER'","TRAVIS_COMMIT":"'$TRAVIS_COMMIT'","TRAVIS_BRANCH":"'$TRAVIS_BRANCH'","TRAVIS_REPO_SLUG":"'$TRAVIS_REPO_SLUG'"}' ;
    export DEPLOY_SIG="sha1=`echo -n "$DEPLOY_CONTENT" | openssl sha1 -hmac $DEPLOY_KEY | sed 's/^.* //'`" ;
    curl -X POST "$DEPLOY_URL" --data "$DEPLOY_CONTENT" -H "Content-Type: application/json" -H "X-Travis-Signature: $DEPLOY_SIG" ;
    fi
